[debug]
address = "127.0.0.1"
port = 8080
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8080
# workers = 2
keep_alive = 5
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }
